### ISSUE TITLE
Blazor serilog ingest

### ISSUE THREAD

**Issue by Adamekjr** [jscarle/LightResults#19]
Hi, I'm having an issue when trying to serialize the error property in Result. Do you have a solution for that by any chance?

   at LightResults.Result`1.get_Error()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.<SerializeAsync>d__9.MoveNext()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.<SerializeAsync>d__9.MoveNext()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.<SerializeAsync>d__9.MoveNext()
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.<WriteResponseBodyAsync>d__5.MoveNext()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeResultAsync>g__Logged|22_0>d.MoveNext()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeNextResultFilterAsync>g__Awaited|30_0>d`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeNextResourceFilter>g__Awaited|25_0>d.MoveNext()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeFilterPipelineAsync>g__Awaited|20_0>d.MoveNext()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<<Invoke>g__AwaitRequestTask|7_0>d.MoveNext()
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__11.MoveNext()
   at Serilog.AspNetCore.Ingestion.SerilogIngestionMiddleware.<Invoke>d__6.MoveNext()
   at Serilog.AspNetCore.RequestLoggingMiddleware.<Invoke>d__10.MoveNext()
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<<Invoke>g__Awaited|10_0>d.MoveNext()

**Comment by Adamekjr** [comment]
My solution below. 
public class ResultJsonConverter : JsonConverter
{
    public override bool CanConvert(Type objectType)
    {
        var isResultType = objectType.IsGenericType && objectType.GetGenericTypeDefinition() == typeof(Result<>);
        return isResultType;
    }

    public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
    {
        var type = value.GetType();

        var isSuccessProperty = type.GetProperty(nameof(Result.IsSuccess));
        var isSuccess = isSuccessProperty != null && (bool)isSuccessProperty.GetValue(value, null);

        var properties = type.GetProperties();

        var obj = new JObject();

        foreach (var prop in properties)
        {
            if (isSuccess && prop.Name == nameof(Result.Error))
            {
                continue;
            }

            var propValue = prop.GetValue(value);
            if (propValue != null)
            {
                obj.Add(prop.Name, JToken.FromObject(propValue, serializer));
            }
        }

        obj.WriteTo(writer);

    }

    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
    {
        throw new NotImplementedException();
    }
}

**Comment by jscarle** [comment]
Hello @Adamekjr,

Thanks for pointing this out. Can you clarify something for me? It looks like from the stack trace that it was the `Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter` which failed, however the converter you showed is from `Newtonsoft.Json`?

**Comment by Adamekjr** [comment]
Yeah, so basically I did this.
builder.Services.AddControllersWithViews()
    .AddNewtonsoftJson(options =>
    {
        options.SerializerSettings.Converters.Add(new ResultJsonConverter());
    }); ;

**Comment by jscarle** [comment]
Do you use or need support for Newtonsoft.Json?

**Comment by Adamekjr** [comment]
I prefer using Newtonsoft.Json over system.text.json but it doesn't matter in this case.

**Comment by Adamekjr** [comment]
Here's an example for the System.text.json:
`
public class ResultJsonConverterFactory : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert)
    {
        return typeToConvert.IsGenericType && typeToConvert.GetGenericTypeDefinition() == typeof(Result<>);
    }

    public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        var type = typeToConvert.GetGenericArguments()[0];
        var converter = (JsonConverter)Activator.CreateInstance(
            typeof(ResultJsonConverter<>).MakeGenericType(new Type[] { type }),
            BindingFlags.Instance | BindingFlags.Public,
            binder: null,
            args: new object[] { options },
            culture: null);

        return converter;
    }
}

public class ResultJsonConverter<T> : JsonConverter<Result<T>>
{
    private readonly JsonSerializerOptions _options;

    public ResultJsonConverter(JsonSerializerOptions options)
    {
        _options = options;
    }

    public override Result<T> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        throw new NotImplementedException();
    }

    public override void Write(Utf8JsonWriter writer, Result<T> value, JsonSerializerOptions options)
    {
        writer.WriteStartObject();
        writer.WriteBoolean("IsSuccess", value.IsSuccess);

        if (value.IsSuccess)
        {
            writer.WritePropertyName("Value");
            JsonSerializer.Serialize(writer, value.Value, _options);
        }
        else
        {
            writer.WritePropertyName("Error");
            JsonSerializer.Serialize(writer, value.Error, _options);
        }

        writer.WriteEndObject();
    }
}

`

**Comment by Hau-Hau** [comment]
Maybe converters should be a part of LighResult.Extensions?

**Comment by jscarle** [comment]
I'm working on the System.Text.Json one at the moment, which can be built-in since its part of the SDK. The Newtonsoft.Json one however will need to be put into an extensions package for sure.

I'm struggling a bit on the Metadata dictionary as the data is sort of getting garbled on the return due to its values being objects.

**Comment by jscarle** [comment]
I decided not to add it to the main package. I want to keep it as stable and pure as possible to allow people to opt-in to what they'd like to use.

I gave up on deserializing results as a round trip operation, the metadata dictionary can't be safely deserialized. I published an initial version for System.Text.Json that supports full serialization including the metadata with type discriminators.

You can add `ResultJsonConverterFactory` to the serializer options and it'll take care of doing both concrete and generic results:
https://www.nuget.org/packages/LightResults.Extensions.Json
